[package]
name = "vending"
version = "0.1.0"
authors = ["djrcoder <djrcode@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"

[[bin]]
name = "vending"
path = "src/main.rs"
